let elementQuery = require('../index.js')

console.log(elementQuery.minWidth)
console.log(elementQuery.maxWidth)
console.log(elementQuery.minWidth)
console.log(elementQuery.maxWidth)
console.log(elementQuery.minChildren)
console.log(elementQuery.children)
console.log(elementQuery.maxChildren)
console.log(elementQuery.minCharacters)
console.log(elementQuery.characters)
console.log(elementQuery.maxCharacters)
console.log(elementQuery.minScrollX)
console.log(elementQuery.maxScrollX)
console.log(elementQuery.minScrollY)
console.log(elementQuery.maxScrollY)
console.log(elementQuery.minAspectRatio)
console.log(elementQuery.maxAspectRatio)
console.log(elementQuery.orientation)